### PR TITLE
Update index.css

### PR DESCRIPTION
**Pull request by Kaushal857**
On hover ,it changes the animation and shadow effect.

### CODE REVIEW

**Comment by Rajssss** [comment]
Thanks for the PR, however as the author of that code is @Faizan-Alam-1 .
So, @Faizan-Alam-1 do you thing that the changes is good and should I merge it here?

**Comment by Faizan-Alam-1** [comment]
yes

**Comment by Faizan-Alam-1** [comment]
I  Reviewed the code. Yes it is a good change.

**Comment by rayak-sil** [comment]
Thanks for the response @Faizan-Alam-1 .

**Pull request merged**
